# Spring Boot application.yaml for MySQL database
spring:
    datasource:
        url: ${JDBC_URL}
        username: ${MYSQL_USER}
        password: ${MYSQL_PASSWORD}
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        database-platform: org.hibernate.dialect.MySQLDialect
        properties:
            hibernate:
                '[format_sql]': true
                dialect: org.hibernate.dialect.MySQLDialect
                jdbc:
                    '[batch_size]': 20
                '[order_inserts]': true
                '[order_updates]': true
    profiles:
        active: ${SPRING_PROFILES_ACTIVE:default}
    
    mail:
        host: ${MAIL_HOST:localhost}
        port: ${MAIL_PORT:587}
        username: ${MAIL_USERNAME:}
        password: ${MAIL_PASSWORD:}
        properties:
            mail:
                smtp:
                    auth: ${MAIL_SMTP_AUTH:true}
                    starttls:
                        enable: ${MAIL_SMTP_STARTTLS_ENABLE:true}
                        required: ${MAIL_SMTP_STARTTLS_REQUIRED:false}
                    connectiontimeout: ${MAIL_SMTP_CONNECTION_TIMEOUT:5000}
                    timeout: ${MAIL_SMTP_TIMEOUT:5000}
                    writetimeout: ${MAIL_SMTP_WRITE_TIMEOUT:5000}
                debug: ${MAIL_DEBUG:false}

server:
    port: ${SERVER_PORT}
    servlet:
        context-path: ${SERVER_CONTEXT_PATH}

logging:
    level:
        root: INFO
        '[org.springframework.web]': DEBUG
        '[org.hibernate]': ERROR
        '[com.weather_found.weather_app.modules.weather]': DEBUG

# JWT Configuration
app:
    jwt:
        secret: ${JWT_SECRET}
        expirationMs: ${JWT_EXPIRATION_MS}

# Weather Module Configuration
weather:
    api:
        openweathermap:
            key: ${OPENWEATHERMAP_API_KEY}
            url: ${OPENWEATHERMAP_API_URL}
        nasa:
            key: ${NASA_API_KEY}
            url: ${NASA_API_URL}

# NASA Earthdata Login Configuration
nasa:
    earthdata:
        username: ${NASA_EARTHDATA_USERNAME}
        password: ${NASA_EARTHDATA_PASSWORD}
        base-url: ${NASA_EARTHDATA_BASE_URL}
    
    # NASA POWER API Configuration  
    power:
        api-url: ${NASA_POWER_API_URL}
        timeout: ${NASA_POWER_TIMEOUT}
        max-retries: ${NASA_POWER_MAX_RETRIES}
        retry-delay: ${NASA_POWER_RETRY_DELAY}
    
    rate-limiting:
        enabled: ${WEATHER_RATE_LIMITING_ENABLED}
        default-limit: ${WEATHER_RATE_LIMIT_DEFAULT}
        dashboard-limit: ${WEATHER_RATE_LIMIT_DASHBOARD}
        search-limit: ${WEATHER_RATE_LIMIT_SEARCH}
        api-limit: ${WEATHER_RATE_LIMIT_API}
    
    security:
        input-validation: ${WEATHER_SECURITY_INPUT_VALIDATION}
        suspicious-activity-logging: ${WEATHER_SECURITY_SUSPICIOUS_LOGGING}
        max-block-duration: ${WEATHER_SECURITY_MAX_BLOCK_DURATION}
    
    async:
        core-pool-size: ${WEATHER_ASYNC_CORE_POOL_SIZE}
        max-pool-size: ${WEATHER_ASYNC_MAX_POOL_SIZE}
        queue-capacity: ${WEATHER_ASYNC_QUEUE_CAPACITY}
    
    data:
        retention-days: ${WEATHER_DATA_RETENTION_DAYS}
        alert-retention-days: ${WEATHER_ALERT_RETENTION_DAYS}
        log-retention-days: ${WEATHER_LOG_RETENTION_DAYS}
